
log:
  path: "../logs/%s.log"
  level: "DEBUG"

lr:
  train: "../resource/ctr_train.csv"
  test: "../resource/ctr_test.csv"
  featureLen: 10000
  learningRate: 0.01
  onebatch: 500
  normal: "l2"
  normalRate: 0.01
  modelPath: "../resource"

softmax:
  train: "../resource/Mnist/mnist_train.csv"
  test: "../resource/Mnist/mnist_test.csv"
  featureLen: 784
  learningRate: 0.01
  onebatch: 10
  normal: "l2"
  normalRate: 0.01
  modelPath: "../resource"