
log:
  path: "../logs/%s.log"
  level: "DEBUG"

lr:
  train: "../"
  test: "../"
  featureLen: 3000000
  learningRate: 0.01
  batchCount: 500
  normal: "l2"
  normalRate: 0.01

softmax:
  train: "../resource/Mnist/mnist_train.csv"
  test: "../resource/Mnist/mnist_test.csv"
  featureLen: 784
  learningRate: 0.001
  batchCount: 500
  normal: "l2"
  normalRate: 0.01